server:
  applicationConnectors:
      - type: http
        port: 8082
  adminConnectors:
      - type: http
        port: 8092
keycloak:
  realm: my-realm
  #realm-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlxGuRIS+Z1Jusv9tOG0ssqrX1/IvCFlz4OWTMeLpSLpWx/ntSmyehgOSDJmDVJ8pI4XGvg/XkBeccXf68zpx6rzM7NBJ1ouT9Mj3CkpXhGt+ry0v6/SKzdOJ5m0pAkR9U2tJ31YzCL3SSprnmPXqiPU8jQa9h9ytlsgOtD0f4lAzIWzPWGulKDVHITsk74GJ2nkqmi0NjX7cO8N0dAdXf+wevCAdfPhr/Qxeapp6/4gs/cLdHLfrfGEdHrZE6UVWveudmyrx1GUYQDMC6z28bEof7z+e17k9pa7RE85Hmt3wRPESa81SjrY84OMlTF5nUxkKDsqKZ7MaQXRMbzgLyQIDAQAB"
  realm-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhKOWdxUSRIl/S5k4DJxr51vGmV+GtGzUvUL1uIBTUf33Os/BMA+xc/6PxbI7BSX0RnN3dT8wnsFgzsVbZzK5cZj3AHbxlroLCcVKxJpUqf0SuiJ8iaaroJ9qluzE8Qo7eMPmLuCzQ1b8QHYe0fQyHCew5l2siNV8h0VUi6WjmlP5BCUKnnbsLouDLGj2Z6mX16BYPucqDSUfDTCDYM9wjXBNuOFJXkcbr6EX7Jt9JDIxXu/kbRqouasP7lQ2+MISvkI8nBHMncyn4aulx9zlNCP3Ic6tKnAsPD8lRvTqz/VrKrSJqcR5ZNDVhvWOJ1mxQ6owPgLe+sNHDg+4o8+hBwIDAQAB"
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: serviceX
  bearer-only: true
  use-resource-role-mappings: false
  credentials:
    secret: f1b72c0e-468d-48fa-aa20-f55685f72692
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO