server:
  applicationConnectors:
      - type: http
        port: 8180
  adminConnectors:
      - type: http
        port: 8190
keycloak:
  realm: test2-realm
  realm-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAha/JOUzNo11WDRvFP+lHwzH+trHsEEPqB/bXS3/OiXw4ns5ITEu+/au2ruv1+eHUJ++52wcyqVzX6u0UwYZtsmrBw9bHM1lx/4iFb2B/fQPGQHyTDCJyUZxiaYAgeP1F+0kJFesp5BuFqwtmsVC2jPcqwWnVRoDU7seqlTnSuiKPG0G2t4BTEr4KKnz6gMZkgxTTtoZ/GPrxOD9DoGyeYoyYDnIebf1rj1hWjKeIJ1wp8Zn3NnCaVnZRcy5xPTV9Fbt5DXHbBTeyEYu9SThbmd1ieGxUWXLwIGmZDJXvCpwXjttbeNLZGtriPtCzHs8QIUeITzMcHKWrcWYF58jONwIDAQAB"
  auth-server-url: http://10.24.130.143:8180/auth
  ssl-required: external
  resource: gateway
  bearer-only: true
  use-resource-role-mappings: true
  credentials:
    secret: c94baaca-f80b-4c52-ad2e-51e572cec14a